baseURL = "/"
languageCode = "en-uk"
title = "Jack E Taylor"
description = "Psychology, Words, Statistics"
theme = "min_night2"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/", "\\.rds$"]
publishDir = "docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Jack E. Taylor"
    description = "Psychology, Words, Statistics"
    info = "I'm a postdoctoral researcher interested in visual word recognition, and how it is that we're able to read so quickly and efficiently. I use EEG, eye-tracking, and behavioural paradigms to look at the early stages of recognising words, especially the processing of orthographic information, and how these stages are influenced by context and expectation. I'm also interested in how we represent and access semantic information like concreteness (glory vs. cliff) and semantic size (tooth vs. whale). I'm a big fan of hierarchical analyses and overly-complicated Bayesian models."
    logo = "jacketaylor_250x250.png"
    twitterAuthor = "@JackEdTaylor"
    githubUsername = "JackEdTaylor"
    osfUsername = "sfcnj"
    accent = "#121929" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Roboto" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "idea" # make this match accent
    highlightLanguages = ["r", "python"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/publication/"
    name = "Publications"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 4

#[[menu.main]]
#    url = "/tags/"
#    name = "Tags"
#    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://github.com/JackEdTaylor"
    name = "fab fa-github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/JackEdTaylor/"
    name = "fab fa-twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.gla.ac.uk/pgrs/jacktaylor/"
    name = "fas fa-university"
    weight = 3

[[menu.icon]]
    url = "https://orcid.org/0000-0003-4765-0118"
    name = "fab fa-orcid"
    weight = 4

[[menu.icon]]
    url = "mailto:j.taylor.3@research.glasgow.ac.uk"
    name = "far fa-envelope"
    weight = 5
